places: 
  type: sprite
  gutter: 5
  resources: 
    - "@OdlPlacesBundle/Resources/public/img/fb/"
    - "@OdlPlacesBundle/Resources/public/img/find/"

css_lib:
  type: css
  less_import_paths: 
    - "@OdlAssetBundle/Resources/public/css/lib/less"
  resources:
    - "@OdlAssetBundle/Resources/public/css/lib/blue_print/screen.css"
    - 
      source_path: /bundles/odlasset/css/lib/jquery.ui/smoothness/
      local: "@OdlAssetBundle/Resources/public/css/lib/jquery.ui/smoothness/jquery-ui-1.8.13.custom.css"
    - "@OdlAssetBundle/Resources/public/css/lib/jquery.jqGrid/ui.jqgrid.css"
    - "@OdlAssetBundle/Resources/public/js/lib/jquery.faceList/facelist_2-0.css"
    - "@OdlAuthBundle/Resources/public/css/form.less"
 
js_lib:
  type: javascript
  resources:
    - "@OdlAssetBundle/Resources/public/js/lib/jquery/jquery-1.5.2.js"
    - "@OdlAssetBundle/Resources/public/js/lib/jquery.ui/jquery-1.4.4.min.js"
    - "@OdlAssetBundle/Resources/public/js/lib/jquery.ui/jquery-ui-1.8.11.custom.min.js"
    - "@OdlAssetBundle/Resources/public/js/lib/jquery.ajaxform/jquery.ajaxform.js"
    - "@OdlAssetBundle/Resources/public/js/lib/jquery.ajaxform/jquery.ajaxform.floatError.js"
    - "@OdlAssetBundle/Resources/public/js/lib/jquery.jqGrid/jquery.jqGrid.src.js"
    - "@OdlAssetBundle/Resources/public/js/lib/jquery.json/jquery.json-2.2.js"
    - "@OdlAssetBundle/Resources/public/js/lib/jquery.faceList/jquery.facelist_2-0.js"
    - "@OdlAssetBundle/Resources/public/js/lib/highcharts/js/highcharts.src.js"
    - "@OdlAuthBundle/Resources/public/js/auth.js"
      
shadow_css:
  type: css
  less_import_paths: 
    - "@OdlAssetBundle/Resources/public/css/lib/less"
  resources:
    - "@ShadowBundle/Resources/public/css/layout.less"
    - "@ShadowBundle/Resources/public/css/main.less"

places_css:
  type: css
  less_import_paths: 
    - "@OdlAssetBundle/Resources/public/css/lib/less"
  resources:
    - "@OdlPlacesBundle/Resources/public/css/layout.less"
    - "@OdlPlacesBundle/Resources/public/css/main.less"
  
shadow_js:
  type: javascript
  resources:
    - "@ShadowBundle/Resources/public/js/main.js"
  
places_js:
  type: javascript
  resources:
    - "@OdlPlacesBundle/Resources/public/js/map.js"
