places: 
  type: sprite
  gutter: 5
  resources: 
    - "@OdlPlacesBundle/Resources/public/img/fb/"
    - "@OdlPlacesBundle/Resources/public/img/find/"

css_lib:
  type: css
  less_import_paths: 
    - "@OdlAssetBundle/Resources/public/css/lib/less"
  resources:
    # blue print
    - "@OdlAssetBundle/Resources/public/css/lib/blue_print/screen.css"
    
    # jquery UI
    - 
      source_path: /bundles/odlasset/css/lib/jquery.ui/smoothness/
      local: "@OdlAssetBundle/Resources/public/css/lib/jquery.ui/smoothness/jquery-ui-1.8.13.custom.css"
    
    # jquery jqGrid
    - "@OdlAssetBundle/vendor/js/jquery-jqGrid/css/ui.jqgrid.css"
    - "@OdlAssetBundle/Resources/public/js/lib/jquery.faceList/facelist_2-0.css"
    - "@OdlAuthBundle/Resources/public/css/form.less"
 
js_lib:
  type: javascript
  resources:
    # jquery is needed first
    - "@OdlAssetBundle/vendor/js/highcharts/lib/jquery-1.5.2.js"
    
    # highcharts
    - "@OdlAssetBundle/vendor/js/highcharts/js/highcharts.src.js"
    
    # jquery UI - customize jQuery UI
    - "@OdlAssetBundle/vendor/js/jquery-ui/ui/jquery.ui.core.js"
    - "@OdlAssetBundle/vendor/js/jquery-ui/ui/jquery.ui.widget.js"
    - "@OdlAssetBundle/vendor/js/jquery-ui/ui/jquery.ui.button.js"
    - "@OdlAssetBundle/vendor/js/jquery-ui/ui/jquery.ui.position.js"
    - "@OdlAssetBundle/vendor/js/jquery-ui/ui/jquery.ui.menu.js"
    - "@OdlAssetBundle/vendor/js/jquery-ui/ui/jquery.ui.autocomplete.js"
    - "@OdlAssetBundle/vendor/js/jquery-ui/ui/jquery.ui.tabs.js"
    
    # jquery jqGrid
    - "@OdlAssetBundle/vendor/js/jquery-jqGrid/js/i18n/grid.locale-en.js"
    - "@OdlAssetBundle/vendor/js/jquery-jqGrid/js/grid.base.js"
    
    # jquery Mobile?
    
    # jquery File upload
    - "@OdlAssetBundle/vendor/js/jquery-file-upload/jquery.iframe-transport.js"
    - "@OdlAssetBundle/vendor/js/jquery-form/jquery.form.js"
    
    # Oneoff Libraries
    - "@OdlAssetBundle/Resources/public/js/lib/jquery.json/jquery.json-2.2.js"
    - "@OdlAssetBundle/Resources/public/js/lib/jquery.faceList/jquery.facelist_2-0.js"
    - "@OdlAssetBundle/Resources/public/js/lib/jquery.ajaxform/jquery.ajaxform.js"
    - "@OdlAssetBundle/Resources/public/js/lib/jquery.ajaxform/jquery.ajaxform.floatError.js"
    - "@OdlAuthBundle/Resources/public/js/auth.js"
      
shadow_css:
  type: css
  less_import_paths: 
    - "@OdlAssetBundle/Resources/public/css/lib/less"
  resources:
    - "@ShadowBundle/Resources/public/css/layout.less"
    - "@ShadowBundle/Resources/public/css/main.less"

places_css:
  type: css
  less_import_paths: 
    - "@OdlAssetBundle/Resources/public/css/lib/less"
  resources:
    - "@OdlPlacesBundle/Resources/public/css/layout.less"
    - "@OdlPlacesBundle/Resources/public/css/main.less"
  
shadow_js:
  type: javascript
  resources:
    - "@ShadowBundle/Resources/public/js/main.js"
  
places_js:
  type: javascript
  resources:
    - "@OdlPlacesBundle/Resources/public/js/map.js"
