imports:
    - { resource: security.yml }
    - { resource: default_parameters.yml }
    - { resource: parameters.php }
    
services:
    annotations.reader: 
        class: %annotations.reader.class%
        calls:
            - [ setAutoloadAnnotations, [ true ] ]
    
framework:
    charset:       UTF-8
    secret: "%csrf_secret%"
    csrf_protection:
        enabled: true
    router:        
        resource: "%kernel.root_dir%/config/routing.yml"
        cache_warmer:   false
    validation:    { enabled: true, enable_annotations: true }
    form:
        enabled: true
    templating:    
        engines: ['twig'] 
        assets_version: ~
        assets_base_urls: %assets_base_urls%

    session:
        default_locale: "%locale%"
        lifetime:       3600
        auto_start:     true
        
    annotations:
        cache:          file
    esi: { enabled: false }

sensio_framework_extra: 
    router:  { annotations: true }

jms_security_extra:
    # If you set-up your controllers as services, you must set this to false;
    # otherwise your security checks will be performed twice.
    secure_controllers: true

    # Whether you want to secure all services (true), or only secure specific
    # services (false); see also below
    secure_all_services: false

    # Enabling this setting will add an additional special attribute "IS_IDDQD".
    # Anybody with this attribute will effectively bypass all security checks.
    enable_iddqd_attribute: false

fos_user:
    db_driver: mongodb
    firewall_name: all
    class:
        model:
            user: Odl\AuthBundle\Documents\UserAuth

doctrine:
    dbal:
        default_connection:       default
        connections:              %db_connections%
    orm:
        auto_mapping: true

doctrine_mongodb:
    default_connection: default
    default_database: default
    auto_generate_hydrator_classes: true
    auto_generate_proxy_classes: true
    connections: %mongodb_connections%
    document_managers: %mongodb_managers%

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    extensions:
        - twig.extension.debug
        - twig.extension.text
    globals: 
        g_facebook: @facebook
        g_layout: ShadowBundle::layout.html.twig

odl_asset:
    asset_resource: "%kernel.root_dir%/config/assets.yml" 
    
stof_doctrine_extensions:
    default_locale: en_US
    orm: ~
    mongodb: ~
        
# Swiftmailer Configuration
swiftmailer:
    transport: gmail
    username:  web@wooshed.com
    password:  uWd8T%M2
