parameters:
    csrf_secret: test-market
    database_driver: pdo_mysql
    database_host: localhost
    database_name: symfony
    database_user: root
    database_password: ~
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: ~
    mailer_password: ~
    locale: en
    doctrine.odm.mongodb.default_document_manager: default
    assetic.yaml_asset_manager.packages: "%kernel.root_dir%/config/assets.yml"
    
imports:
    - { resource: security.yml }
    
framework:
    charset:       UTF-8
    secret: "%csrf_secret%"
    csrf_protection:
        enabled: true
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: "%locale%"
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
#    form:
#        resources: ['AcmeDemoBundle:Form:fields.html.twig']

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: true
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar
                    
doctrine_mongodb:
    default_database: hello_%kernel.environment%
    auto_generate_hydrator_classes: true
    auto_generate_proxy_classes: true
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
    document_managers:  
        default:
            mappings:
                ShadowBundle:
                    type: annotation
                    dir: Documents/
                

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
