parameters:
    csrf_secret: test-market
    database_driver: pdo_mysql
    database_host: localhost
    database_name: symfony
    database_user: root
    database_password: ~
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: ~
    mailer_password: ~
    locale: en
    doctrine.odm.mongodb.default_document_manager: default

services:
    annotations.reader: 
        class: %annotations.reader.class%
        calls:
            - [ setAutoloadAnnotations, [ true ] ]
            
imports:
    - { resource: security.yml }
    
framework:
    charset:       UTF-8
    secret: "%csrf_secret%"
    csrf_protection:
        enabled: true
    router:        
        resource: "%kernel.root_dir%/config/routing.yml"
        cache_warmer:   false
    validation:    { enabled: true, enable_annotations: true }
    form:
        enabled: true
    templating:    
        engines: ['twig'] 
        assets_version: ~
        assets_base_urls: 
            - ~

    session:
        default_locale: "%locale%"
        lifetime:       3600
        auto_start:     true
        
    annotations:
        cache:          file
        
sensio_framework_extra: 
    router:  { annotations: true }

fos_user:
    db_driver: mongodb
    firewall_name: all
    class:
        model:
            user: Odl\AuthBundle\Documents\UserAuth
                
#fos_facebook:
#      file:   %kernel.root_dir%/../vendor/facebook/src/facebook.php
#      alias:  facebook
#      app_id: 170752334654
#      secret: 4261ef8a2167c3ce7bbe8ad03d6b5361
#      cookie: true
      
doctrine:
    dbal:
        default_connection:       default
        connections:
            default:
                dbname:           test
                user:             oodle
                password:         null
                host:             wii
    orm:
        auto_mapping: true
                 
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    extensions:
        - twig.extension.debug
        - twig.extension.text
#    form:
#        resources: ['AcmeDemoBundle:Form:fields.html.twig']

# Assetic Configuration
#assetic:
#    debug:          %kernel.debug%
#    use_controller: true
#    filters:
#        cssrewrite: ~
#        # closure:
#        #     jar: %kernel.root_dir%/java/compiler.jar
#        # yui_css:
#        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

odl_asset:
  asset_resource: "%kernel.root_dir%/config/assets.yml" 

doctrine_mongodb:
    default_database: hello_%kernel.environment%
    auto_generate_hydrator_classes: true
    auto_generate_proxy_classes: true
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
    document_managers:  
        default:
            mappings:
                ShadowBundle:
                    type: annotation
                    dir: Documents/
                OdlAuthBundle:
                    type: annotation
                    dir: Documents/
                OdlPlacesBundle:
                    type: annotation
                    dir: Documents/

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
