parameters:
    csrf_secret: test-market
    database_driver: pdo_mysql
    database_host: localhost
    database_name: symfony
    database_user: root
    database_password: ~
    locale: en
    db_connections: 
        default:
            dbname:           test
            user:             root
            password:         null
            host:             localhost
    mongodb_connections: 
        mongo_recommend: 
            server: mongodb://localhost:27017
            options:
                connect: true
        default:
            server: mongodb://localhost:27017
            options:
                connect: true

    mongodb_managers:
        default:
            mappings:
                OdlAuthBundle:
                    type: annotation
                    dir: Documents/
                ShadowBundle:
                    type: annotation
                    dir: Documents/
                OdlPlacesBundle:
                    type: annotation
                    dir: Documents/
        mongo_recommend: 
            mappings:
                OdlRecommendBundle:
                    type: annotation
                    dir: Documents/
                    
