_asset:
    resource: "@OdlAssetBundle/Controller/AssetController.php"
    type:     annotation
    prefix:   /asset
 
_shadow:
    resource: "@ShadowBundle/Controller/MainController.php"
    type:     annotation
    prefix:  /shadow
 
_auth: 
    resource: "@OdlAuthBundle/Controller/AuthController.php"
    type:     annotation
    prefix:  /auth
    
_user: 
    resource: "@OdlAuthBundle/Controller/UserController.php"
    type:     annotation
    prefix:  /user
    
_places:
    resource: "@OdlPlacesBundle/Controller/MainController.php"
    type:     annotation
    prefix:  /places
