home: 
    pattern:   /
    defaults:  { _controller: ShadowBundle:Main:index }
    
login: 
    pattern:   /login
    defaults:  { _controller: OdlAuthBundle:Auth:login }
    
_asset:
    resource: "@OdlAssetBundle/Controller/AssetController.php"
    type:     annotation
    prefix:   /asset
 
_shadow:
    resource: "@ShadowBundle/Controller/MainController.php"
    type:     annotation
    prefix:  /shadow
    
shadow_char:
    resource: "@ShadowBundle/Controller/CharacterController.php"
    type:     annotation
    prefix:  /shadow/char
 
_auth: 
    resource: "@OdlAuthBundle/Controller/AuthController.php"
    type:     annotation
    prefix:  /auth
    
_user: 
    resource: "@OdlAuthBundle/Controller/UserController.php"
    type:     annotation
    prefix:  /user
    
_places:
    resource: "@OdlPlacesBundle/Controller/MainController.php"
    type:     annotation
    prefix:  /places
    
recommend:
    resource: "@OdlRecommendBundle/Controller/RecommendController.php"
    type:     annotation
    prefix:  /r

grid:
    resource: "@DtcGridBundle/Controller/GridController.php"
    type:     annotation
    prefix:  /grid

market:
    resource: "@DtcMarketBundle/Controller/MarketController.php"
    type:     annotation
    prefix:  /market
    
portfolio:
    resource: "@DtcMarketBundle/Controller/PortfolioController.php"
    type:     annotation
    prefix:  /portfolio
    
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
#    