_asset:
    resource: "@OdlAssetBundle/Controller/AssetController.php"
    type:     annotation
    prefix:   /asset
 
_shadow:
    resource: "@ShadowBundle/Controller/MainController.php"
    type:     annotation
    prefix:  /
 