security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Symfony\Component\Security\Core\User\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        default_provider:
            providers: [in_memory, mongo_provider]
            
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

        mongo_provider:
           id: mongodbo.username_password_provider
           
#    factories:
#        facebook: %kernel.root_dir%/../src/Acme/FacebookBundle/Resources/config/security_factories.xml

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /demo/secured/logout
                target: /demo/
#            anonymous: ~
#            http_basic:
#                realm: "Secured Demo Area"
            
        all:
            pattern: ^/.*
            anonymous: ~

    access_control:
        #- { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
