security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Symfony\Component\Security\Core\User\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        default_provider:
            providers: [in_memory, mongo_provider]
            
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

        mongo_provider:
           id: auth.mongodb.username_password_provider
           
    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false
            
        all:
            form_login:
                provider: fos_userbundle
            anonymous: ~

    access_control:
        #- { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
